# Generated by Django 6.0.2 on 2026-02-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=100)),
            ],
        ),
    ]
