# Generated by Django 6.0.2 on 2026-02-27 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='tags',
            field=models.ManyToManyField(to='main_app.tag'),
        ),
        migrations.CreateModel(
            name='UseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Used')),
                ('context', models.CharField(choices=[('H', 'Home Screen'), ('L', 'Lock Screen'), ('D', 'Desktop')], default='H', max_length=1, verbose_name='Context:')),
                ('wallpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_logs', to='main_app.wallpaper')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
